import {chromium} from 'file:///C:/Users/philip/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {createApp} from 'file:///D:/wenyan_checkin/web-study/backend/server.mjs';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const out=new URL('../verification/ui-2026.09.24.3/',"file:///D:/wenyan_checkin/web-study/scripts/browser-daily-training.mjs");await mkdir(out,{recursive:true});
const app=createApp({databasePath:':memory:',bootstrapInvite:'local-daily-test'});
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+app.server.address().port;
const bank=JSON.parse(await readFile(new URL('../content/bank.json',"file:///D:/wenyan_checkin/web-study/scripts/browser-daily-training.mjs"),'utf8'));
const checks=[],errors=[];
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const contexts=[];
const act=(page,a)=>page.locator('[data-action="'+a+'"]').filter({visible:true}).first();
const login=async page=>{await page.goto(origin);await page.locator('[name=username]').fill('daily-student');await page.locator('[name=password]').fill('local-password-123');await page.locator('#auth-form button[type=submit]').click();await page.waitForTimeout(100);};
const choose=async(page,right)=>{const stem=await page.locator('.answer-panel h2').innerText(),q=bank.questions.find(q=>q.stem===stem);assert.ok(q);const id=right?q.answerId:q.choices.find(c=>c.id!==q.answerId).id;await page.locator('[data-choice="'+id+'"]').click();await page.waitForTimeout(100);await act(page,'submit').click();await page.waitForTimeout(100);await page.locator('.feedback').waitFor();return q;};
const snapshot=async(page,name)=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true});};
try{
 const response=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'daily-student',password:'local-password-123',inviteCode:'local-daily-test'})});assert.equal(response.status,201);
 const ctx=await browser.newContext({viewport:{width:768,height:1024}});contexts.push(ctx);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await login(page);await page.locator('#training-form').waitFor();await page.locator('[data-action="daily-count"][data-count="10"]').click();await page.waitForTimeout(150);assert.equal(await page.locator('#training-form').count(),1);assert.equal(await page.locator('#daily-count').inputValue(),'10');checks.push('Daily-count shortcuts change draft without submitting the settings form');
 for(const checkbox of await page.locator('[data-training-essay]').all())await checkbox.uncheck();
 for(const [id,type] of [['essay-01','vocabulary'],['essay-09','theme']]){await page.locator('[data-training-essay="'+id+'"]').check();for(const checkbox of await page.locator('[data-training-type][data-chapter="'+id+'"]').all())await checkbox.uncheck();await page.locator('[data-chapter="'+id+'"][data-training-type="'+type+'"]').check();}
 await page.locator('#daily-count').fill('3');await snapshot(page,'settings-ipad');await page.locator('#training-form button[type=submit]').click();await page.waitForTimeout(100);await act(page,'daily-start').waitFor();await page.reload();await act(page,'daily-start').waitFor();assert.equal(await page.locator('#training-form').count(),0);checks.push('One-time per-chapter settings persist after reload');
 await snapshot(page,'home-active-ipad');await page.setViewportSize({width:390,height:844});await snapshot(page,'home-active-mobile');await page.setViewportSize({width:768,height:1024});await act(page,'daily-start').click();await page.waitForTimeout(100);await page.locator('.options').waitFor();const wrong=await choose(page,false);assert.equal(await page.locator('.mistake-tag').textContent(),'錯題');await act(page,'next').click();await page.waitForTimeout(100);const pendingStem=await page.locator('.answer-panel h2').innerText();await page.locator('[data-choice]').first().click();await page.waitForTimeout(100);await act(page,'pause').click();await page.waitForTimeout(100);await act(page,'resume').click();await page.waitForTimeout(100);assert.equal(await page.locator('.answer-panel h2').innerText(),pendingStem);assert.equal(await page.locator('.option.selected').count(),1);checks.push('Pause/resume retains exact question and selected draft');
 await act(page,'pause').click();await page.waitForTimeout(100);await act(page,'retry-today').click();await page.waitForTimeout(100);assert.equal(await page.locator('.answer-panel h2').innerText(),wrong.stem);await choose(page,true);await act(page,'next').click();await page.waitForTimeout(100);await page.getByText('返回今日訓練',{exact:true}).click();await page.waitForTimeout(100);checks.push('Wrong question immediately available in separate retry, without waiting');
 assert.match(await page.locator('.home-details').innerText(),/1／3/);assert.equal(await act(page,'retry-today').count(),0);checks.push('Corrected retry not offered again and does not inflate daily total');
 await act(page,'resume').click();await page.waitForTimeout(100);await choose(page,true);await act(page,'next').click();await page.waitForTimeout(100);await choose(page,true);await act(page,'next').click();await page.waitForTimeout(100);await page.getByText('返回今日訓練',{exact:true}).click();await page.waitForTimeout(100);await snapshot(page,'home-complete-ipad');assert.match(await page.locator('.home-details').innerText(),/3／3/);assert.equal(await act(page,'daily-start').count(),0);checks.push('Daily target completes once, with separate retry total');
 await act(page,'training-settings').click();await page.waitForTimeout(100);await page.locator('[data-training-essay="essay-02"]').check();assert.equal(await page.locator('[data-chapter="essay-01"][data-training-type="theme"]').isChecked(),false);await page.locator('#daily-count').fill('20');await page.locator('#training-form button[type=submit]').click();await page.waitForTimeout(100);assert.match(await page.locator('.home-details').innerText(),/3／3/);checks.push('Adding a chapter preserves others; changed daily target does not replace today goal');
 await page.locator('[data-action="nav"][data-page="account"]').filter({visible:true}).first().click();await page.waitForTimeout(100);await act(page,'sync').click();await page.waitForTimeout(100);await page.waitForFunction(()=>document.querySelector('#sync-status').textContent==='已備份');
 const mobile=await browser.newContext({viewport:{width:390,height:844}});contexts.push(mobile);const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await login(phone);await phone.getByText('今日目標已完成',{exact:true}).waitFor();assert.equal(await phone.locator('#training-form').count(),0);await snapshot(phone,'home-mobile');checks.push('Second browser restores settings, same-day target and progress from account sync');
 await phone.evaluate(()=>navigator.serviceWorker.ready);await mobile.setOffline(true);await phone.reload();await phone.getByText('今日目標已完成',{exact:true}).waitFor();await act(phone,'training-settings').click();await page.waitForTimeout(100);await phone.locator('#training-form').waitFor();checks.push('Offline reload includes new daily modules and saved settings');
 assert.deepEqual(errors,[]);await writeFile(new URL('result.json',out),JSON.stringify({result:'PASS',checks,errors,scope:'Isolated in-memory local account; Chromium 768x1024 and 390x844. No production account data or physical iPad.'},null,2));console.log(JSON.stringify({result:'PASS',checks}));
}finally{for(const ctx of contexts)await ctx.close();await browser.close();await new Promise(resolve=>app.server.close(resolve));app.close();}
