import {available,queue} from '../domain/queue.mjs';
import {isDue} from '../domain/review.mjs';
import {esc,button,heading,essayTitle,abilities,empty,quote} from './shared.mjs';
export function libraryView(bank,state,options){
 const pool=available(bank.questions,options),list=queue(bank.questions,options,state),distribution=options.essayIds.map(id=>essayTitle(bank,id)+' '+list.filter(q=>q.essayIds[0]===id).length+' 題').concat(list.some(q=>!q.essayIds.length)?['手法附錄 '+list.filter(q=>!q.essayIds.length).length+' 題']:[]).join(' · ');
 return heading('選幾篇，一起練','從熟悉的句子開始，練出清晰的理解。')+(options.questionIds?'<div class="banner">目前限於從其他入口帶入的 '+options.questionIds.length+' 道題。'+button('clear-subset','恢復全部已選篇章題目','','quiet')+'</div>':'')+'<div class="toolbar">'+button('select-all','全選 16 篇','','secondary')+button('select-prose','只選文言文','','secondary')+button('select-poem','只選詩詞','','secondary')+button('select-none','清空','','quiet')+button('nav','易混詞義對照','data-page="compare"','quiet')+'</div><div class="library-grid">'+bank.essays.map((e,i)=>{const n=bank.questions.filter(q=>q.essayIds.includes(e.id)&&q.status==='reviewed'&&q.active!==false).length;return '<article class="library-card '+(options.essayIds.includes(e.id)?'selected ':'')+(!n?'disabled':'')+'"><label><input type="checkbox" data-essay="'+esc(e.id)+'" '+(options.essayIds.includes(e.id)?'checked':'')+' '+(!n?'disabled':'')+'><div><span class="eyebrow">'+String(i+1).padStart(2,'0')+' · '+(e.kind==='poem'?'詩詞':'文言文')+'</span><h2>'+esc(e.title)+'</h2><p>'+ (n?n+' 道已核對練習題':'題庫待開放')+'</p></div></label></article>';}).join('')+'</div><section class="scope-panel"><h2>這一組的安排</h2><div class="toolbar"><label for="question-count">題數</label><input id="question-count" class="count-field" type="number" inputmode="numeric" min="1" max="100" value="'+options.count+'">'+[10,20,30].map(n=>button('count',n+' 題','data-count="'+n+'"','secondary')).join('')+'<label for="scope">範圍</label><select id="scope"><option value="all" '+(options.scope==='all'?'selected':'')+'>全部題目</option><option value="wrong" '+(options.scope==='wrong'?'selected':'')+'>只練錯題</option></select></div><div class="filter-line"><label>能力 <select id="ability"><option value="">全部能力</option>'+Object.entries(abilities).map(([id,t])=>'<option value="'+id+'" '+(options.ability===id?'selected':'')+'>'+t+'</option>').join('')+'</select></label><label><input type="checkbox" id="appendix" '+(options.appendix?'checked':'')+'> 開啟手法附錄專項</label></div><p class="section-note">已選 '+options.essayIds.length+' 篇 · 可用 '+pool.length+' 題 · 到期 '+pool.filter(q=>isDue(state.memories[q.memoryId])).length+' 題</p><p>'+esc(distribution||'先選擇篇章')+'</p>'+(list.length<options.count?'<p class="banner">這個範圍可組成 '+list.length+' 題；不重複題目或同一知識點湊數。</p>':'')+(options.count<options.essayIds.length?'<p class="banner">本組題數少於所選篇數，未覆蓋篇章會在後續組優先輪到。</p>':'')+'<div class="toolbar">'+button('start','開始均衡混練 →',!list.length?'disabled':'')+'</div><p class="subtle">先到期、再薄弱與未練。跨篇題只在涉及篇章全部選中時出現。</p></section>';
}
export function compareView(bank,options,target='',expanded=false){
 const selected=new Set(options.essayIds),groups=bank.comparisons.filter(g=>g.status==='reviewed'&&(!target||g.target===target));
 const visible=groups.map(g=>({...g,items:g.items.map(item=>({...item,q:bank.questions.find(q=>q.id===item.questionId&&q.status==='reviewed'&&q.active!==false)})).filter(item=>item.q&&(expanded||item.q.essayIds.every(id=>selected.has(id))))})).filter(g=>g.items.length>=2);
 return heading('同一個字，不同的語境','只閱讀對照，不會計為答題或改變複習間隔。')+'<div class="toolbar">'+button('nav','← 返回選篇','data-page="library"','quiet')+button('compare-expand',expanded?'只看已選篇章':'明確加入其他篇章對照','','secondary')+'</div>'+(visible.length?visible.map(g=>'<section><h2>'+esc(g.title)+'</h2><div class="compare-grid">'+g.items.map(({q,meaning,clue})=>'<article class="compare-card"><span class="tag">'+esc(q.essayIds.map(id=>essayTitle(bank,id)).join('／'))+'</span><blockquote>'+quote(q)+'</blockquote><p class="card-answer">'+esc(meaning)+'</p><p>'+esc(clue)+'</p>'+'</article>').join('')+'</div><div class="toolbar">'+button('compare-practice','練習這些用法','data-group="'+esc(g.id)+'"')+'</div></section>').join(''):empty('所選範圍暫無可並列的已核對用法','可明確加入其他篇章查看；原練習組的範圍和題目不變。'));
}

