import {hkDay,addDays,isDue,isWeak} from '../domain/review.mjs';
import {weakness,quickCards,available} from '../domain/queue.mjs';
import {esc,button,heading,essayTitle,abilities,empty,source,quote,navigationIcon} from './shared.mjs';
function homeShortcuts(){
 const entries=[['weakness','薄弱地圖','找到需要鞏固的知識點'],['saved','我的收藏','留住想再讀的重點'],['quick','快速回顧','翻卡重溫薄弱與收藏']];
 return '<nav class="home-shortcuts" aria-label="學習快捷入口">'+entries.map(([page,label,description])=>'<button type="button" class="home-shortcut" data-action="nav" data-page="'+page+'"><span class="home-shortcut-icon '+page+'">'+navigationIcon(page)+'</span><span class="home-shortcut-copy"><strong>'+label+'</strong><span>'+description+'</span></span></button>').join('')+'</nav>';
}
export function homeView(bank,state){
 const today=hkDay(),days=Math.round((Date.parse('2027-04-08')-Date.parse(today))/86400000),firsts=state.firsts.filter(f=>f.day===today),due=Object.values(state.memories).filter(m=>isDue(m)&&!state.completedToday.has(m.memoryId)),unfinished=Object.values(state.sessions).filter(s=>!s.completed).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
 return heading('今天，也讀懂一點','你的文言學習書房')+homeShortcuts()+'<div class="home-grid"><section class="hero"><div class="hero-top"><span class="eyebrow">每天一點 · 累積底氣</span><span class="pill">香港 '+today+'</span></div><div class="hero-content"><div class="countdown"><div class="countdown-label">距你設定的 DSE 中文考試</div><div class="countdown-value">'+Math.abs(days)+'<span>天'+(days<0?'前':'')+'</span></div><div class="exam-date">2027 · 04 · 08</div></div><div class="encouragement"><h2 id="encouragement">不急著讀完，<br>先把一句讀懂。</h2><button class="encouragement-change" data-action="encourage">換一句 ↗</button></div></div><div class="hero-bottom">'+button('nav','衝刺混練 →','data-page="library"')+'<span class="hero-meta">每個語境，都值得細讀</span></div></section><aside class="home-aside"><div class="side-card"><h3>今天的積累</h3><div class="today-stat"><strong>'+firsts.length+'<span>知識點</span></strong><small>每日首次</small></div><div class="today-stat"><strong>'+due.length+'<span>項</span></strong><small>到期與鞏固提醒</small></div>'+button('daily','開始日常複習','','quiet')+'</div><div class="side-card review-card"><h3>考前快速回顧</h3><p>把薄弱重點與收藏，放在眼前。</p>'+button('nav','翻開重點卡片','data-page="quick"','secondary')+'</div></aside></div>'+(unfinished.length?'<div class="section-title"><h2>接著上一次</h2></div>'+unfinished.map(s=>'<div class="saved-row"><h3>'+s.questions.length+' 題 · '+(s.mode==='mixed'&&s.questions.some((q,i)=>i%3===2&&q.responseFormat!=='single-choice')?'含文字自查':'選擇題')+'</h3><p>進度 '+Math.min(s.index+1,s.questions.length)+' / '+s.questions.length+' · '+esc(s.startedAt.slice(0,10))+'</p>'+button('resume','繼續練習','data-session="'+esc(s.id)+'"','secondary')+'</div>').join(''):'')+'<div class="section-title"><h2>找到下一步</h2></div><div class="toolbar">'+button('nav','易混詞義對照','data-page="compare"','secondary')+button('nav','複習日曆與記錄','data-page="history"','quiet')+'</div><p class="footer-note">按所附復習書核對的練習題，非官方真題。考試日由你設定。</p>';
}
export function weaknessView(bank,state,options){
 return heading('哪裡還不穩，一眼看清','每個知識點只取最近一次每日首次；當天重練不會刷高表現。')+'<div class="toolbar">'+button('nav','調整篇章範圍','data-page="library"','secondary')+'</div><div class="table-wrap"><table><thead><tr><th>篇章</th>'+Object.values(abilities).map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+bank.essays.filter(e=>options.essayIds.includes(e.id)).map(e=>'<tr><th>'+esc(e.title)+'</th>'+Object.keys(abilities).map(a=>{const w=weakness(bank.questions,state,e.id,a);return '<td><button class="'+(w.weak?'weak':'')+'" data-action="weak-cell" data-essay="'+esc(e.id)+'" data-ability="'+a+'" '+(!w.total?'disabled':'')+'>'+ (w.status==='unavailable'?'題目待補充':w.status==='unassessed'?'未評估'+(w.pending?' · '+w.pending+' 項待自查':''):w.weak+' 項待鞏固')+'<small>已練 '+w.studied+' / '+w.total+' · 到期 '+w.due+'</small>'+(w.studied?'<small>選擇 '+w.choice+' · 自查 '+w.typing+(w.pending?' · 待自查 '+w.pending:'')+'</small><small>最近 '+esc(w.latest)+'</small>':'')+'</button></td>';}).join('')+'</tr>').join('')+'</tbody></table></div><p class="section-note">樣本量反映已練知識點，不等同整篇掌握率。未練與資料未覆蓋分開顯示。</p>';
}
export function historyView(bank,state){
 const today=hkDay(),schedule=Object.values(state.memories).filter(m=>m.due);
 return heading('把積累留在這裡','複習安排、每日首次與重練記錄')+'<h2>接下來七天</h2><div class="review-calendar">'+Array.from({length:7},(_,i)=>{const day=addDays(today,i),n=schedule.filter(m=>i===0?m.due<=day:m.due===day).length;return '<div class="review-day '+(!i?'active':'')+'"><span>'+(!i?'今天與逾期':day.slice(5))+'</span><strong>'+n+'</strong><em>待複習知識點</em></div>';}).join('')+'</div>'+Object.entries(schedule.reduce((a,m)=>{if(m.due>addDays(today,6))a[m.due]=(a[m.due]||0)+1;return a;},{})).sort().map(([date,n])=>'<div class="calendar-extra">'+date+' · '+n+' 項</div>').join('')+'<p class="review-rule">首次答錯後約 10 分鐘提醒、次日複習；之後到期首次答對，間隔按 2、4、7、15、30、60、90 天增加。提前答對不推遲原安排。同日重練只完成提醒。</p><h2>作答記錄</h2>'+(state.attempts.length?[...state.attempts].reverse().map(e=>{const p=e.payload,q=p.question||{},first=state.firsts.some(f=>f.id===e.id),correct=p.mode==='typing'?state.assessments.get(e.id):p.correct;return '<article class="saved-row"><span class="tag">'+esc(p.day)+'</span><span class="tag">'+(first?'每日首次':'當天重練')+'</span><h3>'+esc(q.stem)+'</h3><p class="history-answer">你的答案：'+esc(p.mode==='choice'?(q.choices?.find(c=>c.id===p.answer)?.text||'暫時不會'):p.answer)+'</p><p>'+ (correct===undefined?'待自查':correct?'原作答：答對／自查完整':'原作答：待鞏固')+' · 原題 v'+esc(p.questionVersion)+'</p><details><summary>當時題目與來源</summary><blockquote>'+esc(q.quote)+'</blockquote><p>'+esc(q.explanation)+'</p>'+source(q)+'</details></article>';}).join(''):empty('還沒有作答記錄','從一組練習開始，記錄會保存在你的帳號。'));
}
export function savedView(bank,state,options){
 const rows=Object.values(state.favorites).filter(f=>f.saved).map(f=>({f,q:bank.questions.find(q=>q.id===f.questionId)})).filter(({q})=>!q||q.essayIds.every(id=>options.essayIds.includes(id))&&(!options.ability||q.ability===options.ability));
 return heading('留住想再看的重點','收藏與答錯分開記錄；收藏不改變複習曲線。')+'<div class="toolbar">'+button('nav','調整篇章與能力篩選','data-page="library"','secondary')+button('saved-practice','收藏混練')+button('saved-quick','收藏快速回顧','','secondary')+'</div>'+(rows.length?rows.map(({f,q})=>'<article class="saved-row"><h3>'+esc(q?.stem||f.questionId)+'</h3><p>'+esc(q?(q.quote||q.essayIds.map(id=>essayTitle(bank,id)).join('／')):'此題目前不可用，收藏仍保留。')+'</p><span class="tag">'+esc(q?abilities[q.ability]:'')+'</span>'+(!q||q.status!=='reviewed'||q.active===false?'<span class="tag">已下架 · 不進新練習</span>':q.version!==f.version?'<span class="tag">題目已更新</span>':'')+'<div class="toolbar">'+button('favorite','取消收藏','data-id="'+esc(f.questionId)+'"','quiet')+'</div></article>').join(''):empty('這個範圍還沒有收藏','答題時按「收藏」，原本的答案和草稿都會保留。'));
}
export function quickView(bank,state,options,quick){
 const cards=quick.cards,idx=Math.min(quick.index,Math.max(0,cards.length-1)),q=cards[idx];
 return heading('考前，把重點再讀一遍','翻卡、展開與「看過了」只記為瀏覽，不計答對。')+(quick.version&&quick.version!==bank.version?'<p class="banner">題庫已更新；保留你上次卡片的位置與原版本。重新選擇上方範圍即可載入最新重點。</p>':'')+'<div class="toolbar">'+button('quick-scope','薄弱重點','data-scope="weak"','secondary')+button('quick-scope','我的收藏','data-scope="saved"','secondary')+button('quick-scope','兩者合併','data-scope="both"','secondary')+button('nav','選擇篇章','data-page="library"','quiet')+'</div>'+(q?'<article class="quick-card"><div class="quick-position">'+(idx+1)+' / '+cards.length+' · '+esc(q.essayIds.map(id=>essayTitle(bank,id)).join('／')||'手法附錄')+'</div><blockquote>'+(q.quote?.trim()?quote(q):esc(q.stem))+'</blockquote><p class="card-answer">'+esc(q.summary||q.choices.find(c=>c.id===q.answerId)?.text)+'</p><p>常見誤區：'+esc(q.misconception||q.choices.find(c=>c.id!==q.answerId)?.explanation)+'</p><details><summary>必要講解與來源</summary><p>'+esc(q.explanation)+'</p>'+source(q)+'</details><div class="toolbar">'+button('quick-prev','上一張',idx===0?'disabled':'','secondary')+button('quick-seen',idx===cards.length-1?'看過了 · 完成':'看過了 · 下一張')+button('quick-practice','轉為練習','','quiet')+'</div></article>':empty(options.quickScope==='saved'?'所選範圍暫無收藏':'暫無個人薄弱記錄','可以改看所選篇章的已核對重點。')+'<div class="toolbar">'+button('quick-all','查看已核對重點','','secondary')+'</div>');
}
export function reportsView(reports){
 const labels={pending:'待發送',received:'已收到',processing:'處理中',corrected:'已修正',replied:'說明已回覆'};
 return heading('我的題目回報','回報不會自動更改答案；維護者會按來源復核。')+(reports.length?reports.map(r=>'<article class="saved-row"><span class="report-status">'+esc(labels[r.status]||r.status)+'</span><h3>'+esc(r.category)+'</h3><p>'+esc(r.detail)+'</p><p class="subtle">'+esc(r.questionId)+' · v'+esc(r.questionVersion)+'</p>'+(r.reply?'<p>回覆：'+esc(r.reply)+'</p>':'')+'</article>').join(''):empty('還沒有題目回報','提交答案後，可在解析下方回報疑點。'));
}

