import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:8792';
if(!origin.startsWith('http://127.0.0.1:'))throw new Error('This fixture script is local-only');
const seed=randomBytes(5).toString('hex'),password='Local-qa-'+randomBytes(12).toString('hex');
const checks=[];
async function api(route,body,token,extraHeaders={}){
 const r=await fetch(origin+route,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),Origin:origin,...extraHeaders},...(body?{body:JSON.stringify(body)}:{})});
 return {status:r.status,body:await r.json()};
}
assert.equal((await api('/api/health')).status,200);
assert.equal((await api('/api/me')).status,401);
assert.equal((await api('/api/auth/register',{username:'qa-'+seed,password,inviteCode:'wrong'})).status,403);
const a=await api('/api/auth/register',{username:'a-'+seed,password,inviteCode:'isolated-cloud-worker-test'});
const b=await api('/api/auth/register',{username:'b-'+seed,password,inviteCode:'isolated-cloud-worker-test'});
assert.equal(a.status,201);assert.equal(b.status,201);
assert.equal((await api('/api/auth/login',{username:'a-'+seed,password:'invalid'})).status,401);
const device=await api('/api/auth/login',{username:'a-'+seed,password});assert.equal(device.status,200);
checks.push('Registration and independent device login with scrypt passwords');
assert.equal((await api('/api/me',null,a.body.token,{Origin:'https://attacker.invalid'})).status,403);
assert.equal((await api('/api/admin/reports',null,a.body.token)).status,403);
checks.push('Origin validation and student/admin permissions');
const bank=await (await fetch(origin+'/content/bank.json')).json();assert.equal(bank.questions.length,2131);
const q=bank.questions[0],now=new Date().toISOString(),id='attempt-'+seed;
const event={id,type:'attempt',createdAt:now,payload:{questionId:q.id,memoryId:q.memoryId,questionVersion:q.version,question:q,submittedAt:now,mode:'choice',answer:'wrong',correct:false}};
let sync=await api('/api/sync',{events:[event]},a.body.token);assert.equal(sync.status,200);assert.equal(sync.body.events.length,1);
assert.equal((await api('/api/sync',{events:[event]},device.body.token)).body.events.length,1);
assert.equal((await api('/api/sync',{events:[]},b.body.token)).body.events.length,0);
checks.push('Cross-device sync, replay idempotency and account isolation');
const favorite={id:'first-'+seed,type:'favorite',createdAt:new Date(Date.now()-5000).toISOString(),payload:{questionId:q.id,saved:true}};
sync=await api('/api/sync',{events:[favorite,{...event,payload:{...event.payload,answer:'changed'}}]},a.body.token);assert.equal(sync.status,409);
assert.equal((await api('/api/sync',{events:[]},a.body.token)).body.events.length,1);
checks.push('SQLite transaction rolls back the entire conflicting sync batch');
const report={id:'report-'+seed,type:'report',createdAt:now,payload:{questionId:q.id,questionVersion:q.version,category:'答案核對',detail:'本地雲端部署驗收'}};
assert.equal((await api('/api/sync',{events:[report]},a.body.token)).status,200);
let admin=await api('/api/auth/register',{username:'teacher',password:'Local-admin-check-2026',inviteCode:'isolated-cloud-admin-test'});
if(admin.status!==201)admin=await api('/api/auth/login',{username:'teacher',password:'Local-admin-check-2026'});
assert.ok([200,201].includes(admin.status));
const reports=await api('/api/admin/reports',null,admin.body.token);const matched=reports.body.reports.find(x=>x.eventId===report.id);assert.ok(matched);
const correction=await api('/api/admin/corrections',{reportId:matched.id,attemptId:id,correct:true,reason:'本地校驗更正'},admin.body.token);assert.equal(correction.status,201);
sync=await api('/api/sync',{events:[]},device.body.token);assert.equal(sync.body.firstObservations[0].correct,true);assert.equal(sync.body.events.find(x=>x.id===id).payload.correct,false);
checks.push('Admin correction changes the effective result while preserving the original answer');
const revision=await api('/api/admin/questions/'+q.id,{status:'reviewed',reason:'本地驗收',revision:q},admin.body.token);assert.equal(revision.status,409);
checks.push('Revision version checked against the deployed asset bank');
const recovered=await api('/api/auth/recover',{username:'a-'+seed,recoveryCode:a.body.recoveryCode,newPassword:password+'-new'});assert.equal(recovered.status,200);
assert.equal((await api('/api/me',null,device.body.token)).status,401);assert.equal((await api('/api/me',null,a.body.token)).status,401);
checks.push('Recovery invalidates every previous session');
const pdf=await fetch(origin+'/content/sources/revision-book.pdf',{headers:{Range:'bytes=0-31'}});assert.equal(pdf.status,206);assert.ok((await pdf.text()).startsWith('%PDF-'));
for(const path of ['/backend/data/study.sqlite','/backend/api.mjs','/.dev.vars'])assert.equal((await fetch(origin+path)).status,404);
checks.push('PDF byte range and private-file isolation');
await mkdir(new URL('../verification/cloudflare/',import.meta.url),{recursive:true});
await writeFile(new URL('../verification/cloudflare/local-result.json',import.meta.url),JSON.stringify({result:'PASS',checks,questionCount:bank.questions.length},null,2));
console.log(JSON.stringify({result:'PASS',checks},null,2));
