import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createApp} from '../backend/server.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'file:///C:/Users/philip/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const bank=JSON.parse(await readFile(new URL('../content/bank.json',import.meta.url),'utf8'));
const app=createApp({databasePath:':memory:',bootstrapInvite:'isolated-content-check'});
await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${app.server.address().port}`;
const checks=[],errors=[];
const folder=new URL('../verification/ui-2026.09.20.2/content-expansion/',import.meta.url);await mkdir(folder,{recursive:true});
let browser;
try{
 const response=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'isolated-content-check',password:'Content-check-only-2026',inviteCode:'isolated-content-check'})});
 if(!response.ok)throw new Error('Fixture account failed');const auth=await response.json();
 browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:768,height:1024}});
 await context.addInitScript(auth=>localStorage.setItem('wenyan-auth-v1',JSON.stringify(auth)),{token:auth.token,user:auth.user});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);await page.locator('.home-shortcuts').waitFor();
 await page.locator('.mobile-nav [data-page="library"]').click();
 if(await page.locator('.library-card').count()!==16)throw new Error('Missing essay cards');
 if(bank.questions.length<=218)throw new Error('Expanded bank not published');
 checks.push({check:'Expanded bank and all sixteen essay cards',questions:bank.questions.length});
 await page.locator('#ability').selectOption('meaning');
 const meanings=bank.questions.filter(q=>q.ability==='meaning'&&!q.tags?.includes('appendix')&&q.active).length;
 await page.waitForFunction(n=>document.querySelector('.scope-panel')?.textContent.includes('可用 '+n+' 題'),meanings);
 checks.push({check:'Meaning filter includes all sentence comprehension and translation questions',available:meanings});
 await page.locator('#ability').selectOption('');
 await page.waitForFunction(n=>document.querySelector('.scope-panel')?.textContent.includes('可用 '+n+' 題'),bank.questions.filter(q=>!q.tags?.includes('appendix')&&q.active).length);
 await page.locator('[data-action="select-none"]').click();await page.locator('#appendix').check();
 await page.locator('[data-action="count"][data-count="10"]').click();
 const total=bank.questions.filter(q=>q.tags?.includes('appendix')&&!q.essayIds.length&&q.active).length;
 if(!(await page.locator('.scope-panel').innerText()).includes('可用 '+total+' 題'))throw new Error('Appendix pool count incorrect');
 await page.reload();await page.locator('.home-shortcuts').waitFor();await page.locator('.mobile-nav [data-page="library"]').click();
 if(await page.locator('[data-essay]:checked').count()!==0||!await page.locator('#appendix').isChecked())throw new Error('Saved appendix-only scope changed after reload');
 checks.push({check:'Explicit empty essay scope survives online reload'});
 await page.locator('[data-action="start"]').click();await page.locator('.answer-panel').waitFor();
 if(!(await page.locator('.source-panel').innerText()).includes('手法附錄'))throw new Error('Appendix heading missing');
 checks.push({check:'Appendix-only practice opt-in',available:total});
 const stem=await page.locator('.answer-panel h2').textContent();const q=bank.questions.find(q=>q.stem===stem&&q.tags?.includes('appendix'));
 if(!q)throw new Error('Displayed question not found');
 await page.locator('[data-action="choose"][data-choice="'+q.answerId+'"]').click();await page.locator('[data-action="submit"]').click();
 await page.getByText('這次答對了',{exact:true}).waitFor();
 if(await page.locator('a.source-link').count())throw new Error('Student source display should be removed');
 const pdf=await context.request.get(origin+q.source.pdfUrl,{headers:{Range:'bytes=0-31'}});
 if(pdf.status()!==206)throw new Error('Underlying source PDF cannot be read');
 checks.push({check:'Correct answer and explanation; source hidden in UI, underlying PDF retained',questionId:q.id,page:q.source.pdfPage});
 await page.screenshot({path:fileURLToPath(new URL('appendix-answer.png',folder)),fullPage:true});
 await page.locator('[data-action="favorite"]').click();await page.locator('[data-action="pause"]').click();
 await page.locator('.home-shortcut[data-page="saved"]').click();await page.getByText(stem,{exact:true}).waitFor();
 await page.locator('[data-action="saved-quick"]').click();await page.locator('.quick-card').waitFor();
 if(!(await page.locator('.quick-position').innerText()).includes('手法附錄'))throw new Error('Quick review appendix title missing');
 checks.push({check:'Appendix favorites and quick review label'});
 await page.locator('.mobile-nav [data-page="home"]').click();
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await context.setOffline(true);await page.reload();await page.locator('.home-shortcuts').waitFor();
 await page.locator('.mobile-nav [data-page="library"]').click();
 if(!(await page.locator('.scope-panel').innerText()).includes('可用 '+total+' 題'))throw new Error('Offline expanded pool unavailable');
 checks.push({check:'Expanded bank available after offline reload'});
 await context.close();
 if(errors.length)throw new Error(JSON.stringify(errors));
 const report={result:'PASS',bankVersion:bank.version,checks,pageErrors:errors,scope:'Isolated in-memory database and Chromium 768px. No production accounts or real iPad Safari used.'};
 await writeFile(new URL('result.json',folder),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser?.close();await new Promise(resolve=>app.server.close(resolve));app.close();}
